/*
Navicat MySQL Data Transfer

Source Server         : Tuan Anh
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : onlinemoviestreaming

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2015-12-23 09:38:50
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for account
-- ----------------------------
DROP TABLE IF EXISTS `account`;
CREATE TABLE `account` (
  `User_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Fullname` varchar(255) NOT NULL,
  `Username` varchar(255) NOT NULL,
  `Pass_word` varchar(255) NOT NULL,
  `Email` varchar(255) NOT NULL,
  `Phone_Num` varchar(255) NOT NULL,
  `Role_ID` int(11) NOT NULL,
  PRIMARY KEY (`User_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of account
-- ----------------------------
INSERT INTO `account` VALUES ('1', 'Vu Tuan Anh', 'tuananh_admin', '4CWWS0CmZterRLIcs1yFXw==', 'tuananh05253@gmail.com', '01697979713', '1');
INSERT INTO `account` VALUES ('2', 'Nguyen Van A', 'vana', 'PqVqWFJvTgDcS4ak/w+Wzw==', 'vana@gmail.com', '01234567899', '2');
INSERT INTO `account` VALUES ('3', 'Tester', 'test', 'BOprjoJFYM3BIxYeMPVPMQ==', 'test@gmail.com', '012345567899', '2');
INSERT INTO `account` VALUES ('4', 'Vu Tuan Anh 12', 'tuananh_admin1', '4CWWS0CmZterRLIcs1yFXw==', 'tuananh05253@gmail.com', '01697979713', '1');
INSERT INTO `account` VALUES ('5', 'Nguyen Van A 1', 'vana1', 'PqVqWFJvTgDcS4ak/w+Wzw==', 'vana@gmail.com', '01234567899', '2');
INSERT INTO `account` VALUES ('6', 'Tester 1', 'test1', '4CWWS0CmZterRLIcs1yFXw==', 'test@gmail.com', '012345567899', '2');
INSERT INTO `account` VALUES ('7', 'abc', 'kuruky', 'BOprjoJFYM3BIxYeMPVPMQ==', 'wind_of_the_sky_211093@yahoo.com', 'abc', '2');

-- ----------------------------
-- Table structure for genre
-- ----------------------------
DROP TABLE IF EXISTS `genre`;
CREATE TABLE `genre` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Genre_Name` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of genre
-- ----------------------------
INSERT INTO `genre` VALUES ('1', 'Series');
INSERT INTO `genre` VALUES ('2', 'Movies');
INSERT INTO `genre` VALUES ('3', 'Romantic');
INSERT INTO `genre` VALUES ('4', 'Comedy');
INSERT INTO `genre` VALUES ('5', 'Fiction');
INSERT INTO `genre` VALUES ('6', 'Action');

-- ----------------------------
-- Table structure for movie
-- ----------------------------
DROP TABLE IF EXISTS `movie`;
CREATE TABLE `movie` (
  `Movie_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Movie_Name` text NOT NULL,
  `Movie_Picture` text NOT NULL,
  `Movie_Actor` text NOT NULL,
  `Movie_Information` text NOT NULL,
  `Movie_Genre` text NOT NULL,
  `Movie_Director` text NOT NULL,
  `Movie_Length` text NOT NULL,
  `Movie_Year` date NOT NULL,
  `Movie_Place` text NOT NULL,
  `Movie_Views` int(11) NOT NULL,
  `Movie_Links` text,
  PRIMARY KEY (`Movie_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=44 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of movie
-- ----------------------------
INSERT INTO `movie` VALUES ('1', 'Oh My Ghost (2015)', 'upload/Oh My Ghost (2015).jpg', 'Lee So-Hyeong,Shin Soon-Ae', ' Content film revolves mainly around the relationship between a young female ghost, mischievous and a discerning chef - who do not believe in ghost stories. This drama script writers accept the comment by Yang Seung Hee. The movie starring actress Park Bo - Young and actor Cho Jung - Seok. Park Bo - Young as Na Bo Sun, kitchen dealing in a hotel. Na Bo Sun is a shy girl and have low self-esteem should not have a friend do next. Since there is a shaman grandmother, so from a young age, Na Bo Sun was able to see and talk to spirits. The story became dramatic when the body Na Bo Sun and soul of a ghost named Shin Soon - Ae combined into one. Cho Jung - Seok Kang as Sun - Woo, worked with Na Bo Sun in role executive chef. A guy with good looks make, plus confident demeanor of a chef made her countless love die, dead tired and Na Bo Sun is one of them. However, up to this moment, the chef guy we have not been able to forget the silhouette of his ex-girlfriend. Kang Sun - Woo started to pay attention to Na Bo Sun more since that fateful reversal of Na Bo Sun.', '3', 'Yoon Je-Won, ', '154 phút', '2015-08-01', 'Korea', '98991', null);
INSERT INTO `movie` VALUES ('2', 'Dragon Blade', 'upload/kiem-rong.jpg', 'Jacky Chan, Adrien Brody, John Cusack', '\r\n<img src=\"/OnlineMovieStreaming/images/kiem-rong.jpg\" width=\"100%\" class=\"images\" />\r\nMovie Sword Dragon set in place under the Western Han Dynasty, the film revolves around the story of Huo An army general (Chan) with the mission to protect the peace for the countries in the Western Regions vassal. With talent, and steadfast love peace, or kick fraternal links with each shouldered the alliance formed with his \"Decision peaceful death\". However, he was the god of time to harm, banish him to the frontier and suffer harsh servitude. Fortunately, Huo An army general was Tiberius (John Cusack) en route to escort Prince Oriental liberation. From there, two army generals heroes mount a confidant confidante same protection ideal justice, peace building. Two people stand together undergo a series of thrilling matches and events full of commotion.', '2', 'Daniel Lee', '126 Phút', '2014-09-17', 'China', '83473', 'upload/kiem-rong.mp4');
INSERT INTO `movie` VALUES ('3', 'Cinderella', 'upload/lo-lem.jpg', 'Helena Bonham, Carter Helena, Bonham Carter,  Stellan Skarsgard, Stellan Skarsgard,  Cate Blanchett, Cate Blanchett,  Derek Jacobi, Derek Jacobi,  Nonso Anozie, Nonso Anozie,  Hayley Atwell, Hayley Atwell', 'Cinderella movie content: Based on the fairy tale of the same name by the brothers Grimm, Cinderella by Walt Disney to debut in the animated version in 1950. It movie tells the story of young girl Ella grief after the death of his mother happily co reviews for his father as a Commercial Drive \"remarried\". Looking forward to seeing your dad smile bloom, eagerly Ella stepmother and her two daughters and her in his house. But when his father died suddenly, Ella suddenly faced with the cruelty and estranged from her stepmother and her two daughters. From small lady, Ella suddenly become a slave in his own house. Despite the mistreatment of her, Ella still happily living and trust in life as teachings of the mother before the first \"always courageous and gentle with everyone.\"', '1', 'Kenneth Branagh', '125 Phút', '2015-05-01', 'US', '221', null);
INSERT INTO `movie` VALUES ('4', 'Divergent 2: Insurgent', 'upload/nhung-ke-noi-loan.jpg', 'Yoon Hyun ,Soo Ae', 'Insurgent is the second part of the movie Divergent. In this section, the threat implicit in the social system began to surface, and enough power to cope with it, Tris must continue to conquer his own fears in his own dreams . Tris brings the qualities of the two subdivisions are Dauntless and Abnegation as Tris, which meant that she faced the loss of their loved ones the most.', '2', 'Soo Ae', '185 Phút', '2015-05-02', 'US', '3366', null);
INSERT INTO `movie` VALUES ('5', 'I Fine Thank You Love You', 'upload/I Fine Thank You Love You.jpg', 'Joe Pantoliano,', 'Pleng - an English tutor beautiful and graceful. Her everyday life suddenly changes when she was one of the students asked for help to be able to split up his Thai boyfriend called Gym. Unfortunately not understand English should Gym pupil Pleng recorded voice messages and through interpreters Pleng him. Meanwhile, Pleng fall in love with one of her other students, \"Pruek\" - handsome guy from a good family. He is a romantic person always looking to do Pleng surprised. Eventually they became a couple. \" I Fine..Thank you..Love You \"is a love story\" ungrammatical \"shows that the beauty of imperfection can surpass perfection', '3', 'John Cusack', '75 Phút', '2015-07-01', 'US', '255', null);
INSERT INTO `movie` VALUES ('6', 'Superman and the  Elite', 'upload/sieu-nhan-va-elite.jpg', 'Uma Thurman, Melina Kanakaredes, Julian Richings, Bonita Friedericy, Rosario Dawson, Catherine Keener, Kevin McKidd', 'Superman Vs. the Elite is a movie based on the latest animated comics of DC Comics. The film is based on the story \"What is So Funny About Truth, Justice and the American Way?\" Joe Kelly, said the fight between Superman and The Elite - one group of people have superpowers, willing to kill the other supervillain not bear the constraints of morality and not murder as Superman', '4', 'Daniel Padilla', '30 Phút', '2015-06-09', 'US', '3543', null);
INSERT INTO `movie` VALUES ('7', 'PURE LOVE', 'upload/tinh-yeu-trong-sang-falling-for-innocence-2015.jpg', 'Jung Kyung Ho, Kim So Yeon, Yoon Hyun ', 'Kang Min Ho ( Jung Kyung Ho ), a rich guy Sons moment eviction because the sudden death of the father. Undergo a heart transplant surgery, his personality changed. He felt strange vibrations and gradually she falls in love with his secretary Kim Soon Jung (Kim So Yun) Beside her, he learned the true meaning of \"love\" and \"happiness\". But love always be challenges and Joon Hee ( Yoon Hyun Min ) will create a bizarre love triangle. A romance emotional but ...', '3', 'Ji Young Soo', '120 phút', '2015-08-01', 'Korea', '1534', null);
INSERT INTO `movie` VALUES ('8', 'BELIEVE ME AGAIN', 'upload/hay-tin-em-them-lan-nua-got-to-believe-2014.jpg', 'Kathryn Bernardo, Daniel Padilla, Carmina ', 'Get news video content you one more time: How to recognize when no memory? \"The scariest thing in life is not death. Scarier than death, thatis forgotten. \" Turning around the story of two people trying to find every bit of the past, battling dementia to try to identify each other, and jointly overcome obstacles thousands stumbling over the many thorny path to come together again, \"Believe me again\" is a film filled with sobbing about love and forgetfulness ... Movie about Joaquin (Wacky nickname), he grew up with a stray bullet stuck in the brain, besides the mother harsh wealth and Cristina (nickname Chichay), girl housework fun, upbeat, with a warm heart. Wacky always tried to live independently and therefore, he wants to city college. Unable to shake the will of the son, Mrs. Juliana, Wacky mother had sought to Chichay, maid whom she trusted, take care Wacky. On one side is the young scholar, unprotected as downy , a side of spring green young women are full of life. They are like two opposing entities, meet and gradually fell in love as fate, love each other like a wind irresistible, romantic and sweet, passionate and enthusiastic. On the other, they both draw up how beautiful dream dreams ', '2', 'Cathy Garcia-Molina', '160 Phút', '2015-09-15', 'Thái Lan', '5524', null);
INSERT INTO `movie` VALUES ('9', 'Do not Be swayed ', 'upload/xin-dung-xa-anh-dont-be-swayed-2008.jpg', 'Hong Eun hee, Kim Da in, Sunwoo Eun ', '| the emotional drama Korea, the film revolves around the battle between the two sisters emotional design and So Hyun Mi Jung. So Hyun is a sister of talent, with excellent flavor beautiful beauty heaven but also ambitious in this life. However Mi Jung was a girl who loved the romantic, gentle personality and thoughtful, always for his passionate love for music and pursue it to the end. But things do not stop at the Korean film, all those awkward scenes from the Mi Jung starts fiancé met So Hyun. After that moment Mi Jung did not restrain their feelings and falls in love with her boys - boys marrying his sister. Everything will go far do when accidentally became two different rival. Please see the movie ', '3', 'Lee Hong Goo', '100 Phút', '2015-10-01', 'Korea', '23452', null);
INSERT INTO `movie` VALUES ('10', 'Fast & Furious 7', 'upload/qua-nhanh-qua-nguy-hiem-7.jpg', 'Vin Diesel, Paul Walker, Dwayne Johnson, Michelle Rodriguez, Jordana Brewster, Tyrese Gibson, Chris Bridges, Lucas Black, Jason Statham', 'Furious 7 (also known as the Furious 7 and Furious Seven) is a film of American action in 2015. This is the sequel to the 2013 film Fast & Furious 6 and also the seventh movie in the Fast & Furious franchise. The film was scripted by Chris Morgan and directed by James Wan, with the presence of stars like Vin Diesel, Paul Walker, Dwayne Johnson, Michelle Rodriguez, Jordana Brewster, Tyrese Gibson, Ludacris, and Jason Statham Lucas Black. With three previous films set in between episodes 2 Fast 2 Furious (2003) and The Fast and the Furious: Tokyo Drift (2006), Furious 7 is the first film in the series has events Tokyo Drift back. The film marks the final appearance of actor Paul Walker, who died on November 30, 2013 while only completed half of filming. After the death of Walker, the shooting was delayed because the scenario should be rewritten, and two of his brothers Caleb and Cody Walker is used to stunt remaining scenes. Furious 7 was released on April 3, 2015. The film was released internationally with 3D format ', '4', 'James Wan', '134 Phút', '2015-05-01', 'US', '2443', null);
INSERT INTO `movie` VALUES ('11', 'Dai Gia Chan Dat 2015', 'upload/dai-gia-chan-dat-2015.jpg', 'Bình Trọng, Quang Tèo, Chiến Thắng, Thu Huyền, Kim Xuyến', 'Dai Gia barefoot Part 5 Still as every year, shaping his main two Meters and the two giant half-season, to learn to do. Mr. Tich still find ways gouged his money A. The two main characters are still incurable disabilities philandering. Even his wife still has to do to the look \"rehab girl\" for her husband. Ministry of film promises many unique situation amusing. Of course, as far as performance goes, the audience should know my dear colleagues and more. This affection for those very important artists. So, I do not feel tired or pressure or anything heavy shoulder. Despite more than 50 years old but compared with other young people in the group, I was still very healthy. Comedy Festival in 2015 , so I did not hesitate to go takes a lot, takes away. Though famous but not labor nor eat. Nobody suddenly brings home money to their courtesy at all. ', '4', 'Trần Bình Trọng', '120 Phút', '2014-12-24', 'Việt Nam', '3254', null);
INSERT INTO `movie` VALUES ('12', 'Once in a Summer', 'upload/Once in a Summer.jpg', 'Byung-hun Lee, Soo Ae, Choi Deok Mun,', ' To avoid the control of the father, Yoon involved in extra-curricular activities of the school in a remote rural area. Actor starred include Lee Byung Hun, Soo Ae, Oh Dal Su, Lee Se Eun Jeong Seok Yong, Lee Hae Eun Jo Geun-shik with the director. You are watching movies that summer Once In A Summer or 2006, this is the movie brings emotional factors. Here he met Suh, prostitute working in a small library. 121 minutes long movie and was introduced in 2006. The passage of time and affection between Yoon and Suh was raised under. But both suffer separation when a student demonstration took place and both were arrested Suh Yoon with giam.- titine –', '6', 'Katherine Crockett', '140 phút', '2015-11-27', 'Korea', '1434', null);
INSERT INTO `movie` VALUES ('13', 'VIY', 'upload/VIY.jpg', 'Viktor Bychkov, Aleksey Chadov, Jason Flemyng, Andrey Smolyakov, Agnia Ditkovskite, Yuriy Tsurilo, Olga Zaytseva, Aleksandr Yakovlev, Igor Jijikine, Valeriy Zolotukhin, Nina Ruslanova, Ivan Mokhovikov, Anatoliy Gushchin, Aleksey Petrukhin, Aleksandr Karpov,', 'Jonathan Green early 18th century began the journey \"science\" itself to draw maps from Western Europe to Eastern Europe. After going through Transylvania and the Carpathian Mountains pass, he finds himself lost in a mysterious small village located in a forest located in Ukraine. Disoriented with dense fog led him to \" cursed place \"is. Those who live here unlike anyone he had ever seen before. The villagers, after digging a deep moat to separate themselves from the rest of the world, they nourish faith \"innocence\" that can save themselves from evil, without realizing the wickedness that has dominated treatment in their hearts and awaits a chance to possess and destroy the world.', '4', 'Aleksandr Karpov', '150  phút', '2015-11-19', 'US', '353', null);
INSERT INTO `movie` VALUES ('14', 'SAVIOR TRAVELING THROUGH TIME', 'upload/SAVIOR TRAVELING THROUGH TIME.jpg', 'Hoắc Kiến Hoa, Cảnh Điềm, Quách Phẩm Siêu,', 'In the film , the Wallace Huo will play one time novelists Furniture, facing bad luck in life and no one appreciated. In 1 Times accidentally traveled through space and time to the ancient Tang Dynasty. Fate has pushed him to become a savior and a hero in the eyes of people here. In the Tang Dynasty, people prefer chubby beauty, beautiful girls are the girls fat and therefore, reincarnation wings will play 1 \"female Illusion\" (ugly girl) because her body too thin. Create an eye-catching image of her and hilarious. She said she is very excited with the image and the role she always wanted to appear in this ', '4', 'Quách Phẩm Siêu', '125 phút', '2015-11-28', 'China', '3534', null);
INSERT INTO `movie` VALUES ('15', 'EARTH\'S FINAL HOURS', 'upload/EARTHS FINAL HOURS.png', 'Julia Benson, Cameron Bright, Robert Knepper, Julia Maxwell, Michael Kopsa, Roark Critchlow, Bruce Davison, Alex Zahara, David Richmond-Peck, Gardiner Millar, Ali Liebert, Hiro Kanagawa, Jennifer Shirley, Isaiah Adam, Douglas Chapman,', 'After dense matter from an earth hits exploding white hole, rotation of the planet was destroyed. A team of government agents must locate a lost satellite network that is the only hope of the world for survival ... ', '4', 'Douglas Chapman', '135 phút', '2015-11-11', 'US', '345423', null);
INSERT INTO `movie` VALUES ('16', 'DOOMSDAY PROPHECY', 'upload/DOOMSDAY PROPHECY.jpg', 'A.J. Buckley, Jewel Staite, Alan Dale, Bruce Ramsay, Rick Ravanello, Gordon Tootoosis, Matthew Kevin Anderson, Roseanne Supernault, Hiro Kanagawa, Jerry Wasserman, Douglas Chapman, Matthew Walker, Phillip Mitchell, Lori Triolo, Kate Gajdosik,', '•	An editor (AJ Buckley) and an archaeologist (Jewel Staite) hunt mystery novel of a prophet. When the writer was found dead, the editor can be a device that allows him to see the future of geological nightmare coming will affect the planet. Doomsday prophecy .... What strange things started to happen with the disappearance of the Black Sea, then engulf the crater by the quake. Officials found that all these things are happening on the novel \'Doomsday Prophecy\' of Rupert Crane who previously wrote many novels about the disaster that happened earlier ...', '4', 'Hal Myshrall', '142 phút', '2015-11-19', 'England', '24345', null);
INSERT INTO `movie` VALUES ('17', 'SNOWMAGEDDON', 'upload/SNOWMAGEDDON.jpg', 'David Cubitt, Laura Harris, Dylan Matzke, Magda Apanowicz, Jeffrey Ballard, Lorne Cardinal, Michael Hogan, Donavon Stinson, Amitai Marmorstein, Teach Grant, Leanne Lapp, Haig Sutherland, Carolyn Adair, Michele Cummins, Hal Myshrall,', 'Alaska towns on the brink of forest destroyed by a mysterious snow globe appear at the doorstep and was wrapped as a Christmas present. What happens in it can cause catastrophic destruction in the world really. 18. THE LIGHTNING THIEF \r\n•	Content Lightning Theif movie\r\nAlaska towns on the brink of forest destroyed by a mysterious snow globe appear at the doorstep and was wrapped as a Christmas present. What happens in it can cause catastrophic destruction in the world really', '4', 'Katherine Crockett', '167 phút', '2015-11-19', 'US', '532', null);
INSERT INTO `movie` VALUES ('18', 'THE LIGHTNING THIEF', 'upload/THE LIGHTNING THIEF.jpg', 'Logan Lerman, Brandon T. Jackson, Alexandra Daddario, Jake Abel, Sean Bean, Pierce Brosnan, Steve Coogan, Uma Thurman, Melina Kanakaredes, Julian Richings, Bonita Friedericy, Rosario Dawson, Catherine Keener, Kevin McKidd, Joe Pantoliano,', 'Percy Jackson always had trouble in high school, but it turns out that just the simple matter of puberty. And challenge he will face is that Percy discovers that his father is Poseidon, the god of the seas, and that means that Percy is a demigod! Meanwhile, Zeus, king of the gods, has accused Percy of stealing his ultimate weapon - the lightning power. And now, the life of Percy fall into the whirlpool of danger, and you have to prepare for a big adventure, with thunderstorms occasion danger awaiting the world pour down. Percy will have to go to a special place called Camp Half Blood to annealing ', '4', 'Joe Pantoliano', '80 phút', '2015-11-19', 'duc', '345', null);
INSERT INTO `movie` VALUES ('19', 'INSIDE OUT', 'upload/INSIDE OUT.jpg', '', 'Percy Jackson always had trouble in high school, but it turns out that just the simple matter of puberty. And challenge he will face is that Percy discovers that his father is Poseidon, the god of the seas, and that means that Percy is a demigod! Meanwhile, Zeus, king of the gods, has accused Percy of stealing his ultimate weapon - the lightning power. And now, the life of Percy fall into the whirlpool of danger, and you have to prepare for a big adventure, with thunderstorms occasion danger awaiting the world pour down. Percy will have to go to a special place called Camp Half Blood to annealing ', '3', 'Taraji P. Henson', '90 phút', '2015-12-18', 'US', '523', null);
INSERT INTO `movie` VALUES ('20', 'Ricki and the Flash', 'upload/RICKI AND THE FLASH.jpg', 'Mamie Gummer, Meryl Streep, Sebastian Stan, Rick Springfield, Kevin Kline, Ben Platt, Carmen Carrera, Audra McDonald, Charlotte Rae, Maria Di Angelis, Liz Celeste, Melanie Marie, Hailey Gates, Katherine Crockett,', 'Ricky & The Flash movie is about a rock singer as passionate about her career, she has no close relationship with the children and when her daughter malfunction in marriage, she had no way to help her . By love you, what flowers she had strained relations for years and rediscovered family happy. Ricki and the Flash attention with the participation of famous actress Meryl Streep in the role of a singer Rock is trying to reconnect with family sentiment. After 19 Oscar nominations, the return of Meryl Streep in the film brings the expectation of 20 round of nominations in a career full of brilliant acting of her. ', '3', 'Katherine Crockett', '110 phút', '2015-11-01', 'US', '176548', null);
INSERT INTO `movie` VALUES ('21', 'Absolutely Anything', 'upload/Absolutely Anything.jpg', 'Kate Beckinsale, Simon Pegg, Robin Williams, Terry Gilliam, Joanna Lumley, John Cleese, Rob Riggle, Eddie Izzard, Eric Idle, Terry Jones, Michael Palin, Marianne Oldham, Meera Syal, Robert Bathurst, Emma Pierson,', 'Ministry film revolves around the story of Neil Clarke (Pegg) - a grade II teacher suddenly found itself able to do anything she wants. This power was given to him by a group of aliens is always watching you from the universe. Neil did not know that, the way he uses things special powers that will decide the fate of all mankind ... Just struggling with magical spells that Neil has to find ways to win the hearts of Catherine (Beckinsale) - Girls living in the apartment downstairs. And he did thanks to the help of a loyal friend is the dog, Dennis (voiced by Robin Williams). Meanwhile, ex-boyfriend of Catherine had suddenly appeared to revenge. Does Neil has used his power correctly and reasonable? Will he be able to get the girl of your dreams? Does Neil Dennis can help achieve your goal? The fate of the planet is completely dependent on the actions of Neil.', '3', 'Emma Pierson', '92 phút', '2015-10-13', 'US', '235', null);
INSERT INTO `movie` VALUES ('22', 'Are We There Yet', 'upload/Are.jpg', 'Ice Cube, Nia Long, Aleisha Allen, Philip Bolden, Jay Mohr, M.C. Gainey, Tracy Morgan, Henry Simmons, Ray Galletti, Viv Leacock, Casey Dubois, J.B. McEown,', 'Suzanne was divorced and had two children: 7 year old boy and girl Kevin Lindsey was 11 years old. They are always present mischief with the men want to date her. And guys who do not like kids Nick is inevitable that when you have feelings for Suzanne. On the occasion of New Year, Nick must bring the children to Vancouver, where Suzanne was at work and on the way he was not placed in a situation less phen cry smile they cause. ', '3', 'J.B. McEown', '100 phút', '2015-09-15', 'US', '23523', null);
INSERT INTO `movie` VALUES ('23', 'Zhenitba Balzaminova', 'upload/Zhenitba Balzaminova.jpg', 'Georgiy Vitsin, Lyudmila Shagalova, Lidiya Smirnova, Ekaterina Savinova, Zhanna Prokhorenko, Lyudmila Gurchenko, Tamara Nosova, Nikolay Kryuchkov, Rolan Bykov, Inna Makarova,', 'Balzaminov wedding, produced by Mosfilm company in 1964, based on the eponymous comedy classic playwright ANOstrovski, the entire film is the story of a guy named officer Balzaminov obscure, poor fit just fans, but always dreamed to get his wife and children, the rich just beautiful ... had some comedy movies through dialogue is essential. ', '6', 'Inna Makarova', '121 phút', '2015-09-14', 'US', '5867', null);
INSERT INTO `movie` VALUES ('24', 'MY TEACHER, MR. KIM', 'upload/MY TEACHER, MR. KIM.jpg', 'Cha Seung Won, Hie-bong Byeon, Ji-ru Sung, Won-mi Kim, Jae-eung Lee,', 'Kim Bong-doo is an English teacher in our young a primary school in Seoul. The complaint sent to the row which caused him to transfer to a school in the remote mountains and only true five students. Too bored with life in the sticks lack everything, Kim Bong-doo incubated attempt to get back to the city. He created a program to learn after school and ads is to develop special talents of individual students, to help them enjoy a better education in Seoul. However, in contrast to the evil intentions of Kim, this program received unexpected good results prompted management to reconsider the closure of schools', '3', ' Jae-eung Lee', '142 phút', '2015-09-21', 'Korea', '7456', null);
INSERT INTO `movie` VALUES ('25', 'Kill Zone', 'upload/Kill Zone.jpg', 'Chung Tử Đơn, Hồng Kim Bảo, Nhậm Đạt Hoa, Ngô Kinh, Liêu Khải Trí,', 'Ministry of film is a confrontation between police and a gang name wise and his assistant, an accidental killer. These dramatic circumstances, the mixed martial arts spectacular performances, the actors eat shoulders ... the film has pulled the audience back to the action genre characteristic of Hong Kong.Vien Hong Kong police investigate Chan (Simon Yam) is living the last moments of life. His goddaughter is an orphan whose father was the ringleader of a gang of Hong Kong killed because the key witness in a case. Knowing you have a tumor in the head, Chan is determined at all costs to begin by being cruel PO gangster (Sammo Hung). In partnership with him in this task is Ma (Donnie), who will replace his position. Two men and engage in a war without mercy and face a cold-blooded killer, right arm of PO (Wu Jing). ', '2', 'Liêu Khải Trí', '143 phút', '2015-10-12', 'China', '65479', null);
INSERT INTO `movie` VALUES ('26', 'KILL BILL: VOL 1', 'upload/KILL BILL.jpg', 'Uma Thurman, David Carradine, Daryl Hannah,', 'Bride Avenger The main character, known as \"The Bride\", is a member of the deadly Viper Squad assassination, led by her lover, \"Bill\". After realizing she was pregnant with Bill\'s child, \'Bride\' has decided to escape her life as a killer. She fled to Texas, met a young man who, on the day of their wedding rehearsal was shot dead by an angry and jealous Bill (with the support of the Viper Squad who assassinated). Four years later, the \'bride\' awakens from a coma, and discovered her gone. She, then, decides to seek revenge when five people destroyed her life and killed her baby. The story of Kill Bill Volume I begins. Written by JD ', '2', 'Daryl Hannah', '150 phút', '2015-09-21', 'US', '7465', null);
INSERT INTO `movie` VALUES ('27', 'Bloody Destiny', 'upload/BLOODY DESTINY.jpg', 'Yun-su Choi, Hito,', 'Indomitable Difficult to find any information on this - but from the trailer of what we know is that it features Beardy in gangster mode, seems to be a kung-fu combination of Muay Thai and , and there is a story that is like something like a prequel RZA gang fight in \"Tom Yum Goong 2 \'. A recipe for success? Controversial, but if this is the same with the \'Who I am?\' remake pointed out that the mainland are turning their focus to do the martial arts film, then perhaps we should not complain. Let\'s just hope there is some action suit', '2', 'Yun-su Choi', '85 phút', '2015-08-10', 'Korea', '74567', null);
INSERT INTO `movie` VALUES ('28', 'THE KARATE KID', 'upload/THE KARATE KID.jpg', 'Thành Long, Jaden Smith, Taraji P. Henson,', 'Karate Shop Boys video content: 12 year old boy Dre Parker (Jaden Smith) could have been one of the kid in Detroit, but his mother Dre (Taraji P. Henson) move to work in Beijing, China; Dre mother should go to Beijing to live. The first day of school, Dre has loved a classmate Mei Ying, but cultural differences make the relationship so difficult. Even, Dre\'s feelings make an enemy of the class you, Cheng. In the land of kung fu, Dre knows only a little karate, and Cheng puts \"the karate kid\" with ease. There are no friends in a strange land, Dre has no choice but he has managed but maintenance man Mr. Han (Jackie Chan), who is a master of kung fu. As a teacher, he teaches Dre that kung fu is not to fight, but maturity and calm. But Dre realizes that facing down the bullies will be the fight of his life with. ', '2', 'Taraji P. Henson', '190 phút', '2015-09-28', 'China', '456', null);
INSERT INTO `movie` VALUES ('29', 'ZU WARRIORS', 'upload/ZU WARRIORS.jpg', 'Trịnh Y Kiện, Cổ Thiên Lạc, Chương Tử Di, Trương Bá Chi, Đàm Diệu Văn, Hollow, Hồng Kim Bảo,', 'In the 15th century, when the civil war broke out repeatedly in the west of China. Many people were massacred in the battle. To find a way of living, Yin Ting, a young teenager jumping over ravines Zu, where he met Ting Yin and a monk named Hsiao Yu. These are two players martial stamina. Yin Ting received them as masters. Three teachers and students receive a daunting task that is recovered two swords to lower the vampire crowd before they destroy the world. ', '2', 'Taraji P. Henson', '80 phút', '2015-09-20', 'China', '7456', null);
INSERT INTO `movie` VALUES ('30', 'BUBBLEGUM', 'upload/BUBBLEGUM.jpg', 'Lee Dong Wook, Jung Ryu Won, Lee Jong Hyuk, Park Hee Bon, Park Won Sang,', ' Ri busy Hwan Park was director of the hospital medicine and care for his mother. He has her best friend from childhood is Kim Haeng Ah - the impatient and clumsy trrong 8 years working as a radio producer. Despite many shortcomings, but they are looking for the happiness together. Is happiness has smiled at them? ', '1', 'Park Won Sang', '108 phút', '2015-08-16', 'China', '465', null);
INSERT INTO `movie` VALUES ('31', 'The Blacklist Season 3', 'upload/The Blacklist Season 3.jpg', 'James Spader, Megan Boone, Diego Klattenhoff, Joe Carnahan, Vincent Misiano, David Platt,', 'Part 3 continues with former government operative Raymond \"Red\" Reddington ( James Spader ) is a top target of the FBI hunted for a decade and suddenly FBI headquarters to surrender voluntarily, supported the proposal to arrest terrorists have long thought dead - Ranko Zamani, with conditions only just talked to Elizabeth \"Liz\" Keen - a new employee of the FBI. The story starts from there ...', '1', 'David Platt', '110 phút', '2015-09-13', 'US', '7465', null);
INSERT INTO `movie` VALUES ('32', 'LIMITLESS', 'upload/LIMITLESS.jpg', 'Jake McDorman, Bradley Cooper, Jennifer Carpenter, Hill Harper,', '(Limitless) is an action film , a dramatic comedy, revolves around the story of Eddie Morra (by Bradley Cooper plays), a writer of \"class fat\", lives in a shabby apartment in New York. While depressed to the extreme of work, financial and emotional, Eddie accidentally former brother in law introduced for a \"magic pill\" - a drug being tested is called NZT - likely help to promote full drink brain capacity, can see through phenomena, analyze and conduct extraordinary acumen. Thus, Eddie suddenly become intelligent outstanding. He works with the full mind and superhuman performance. From a scruffy appearance, sloppy, transforms him into a gentleman, charming, radiant shine. \"Thua heady win,\" Eddie decided to quit writing and proudly sit became a triumphal investors on the stock market as well as city Wall', '5', 'Hill Harper', '80 phút', '2014-10-27', 'US', '7465', null);
INSERT INTO `movie` VALUES ('33', 'SUPERGIRL SEASON 1', 'upload/SUPERGIRL SEASON 1.jpg', 'Melissa Benoist, Ben Begley, Laura Benanti,', 'Supergirl starring Melissa Benoist , star of movies playing Kara Zor Glee - El, Superman\'s cousin. She later escaped Krypton and explosions in Earth resides under the guise of an ordinary girl named Kara Devengers. But then at the age of 24, Kara decided to use his supernatural ability to become a superhero. After the success of the series of comic characters of DC Comics such as Arrow and The Flash, this is a drama desirability of CBS. Through the trailer we can see films targeting teens with bright colors, matching witty personality Kara Devengers. This can be considered a wise step when the current trend is \"night of\" superhero films (typically as bold series of violence and darkness of Marvel\'s \"Daredevil\") is growing. But the fan base has a large comic teenagers and children, so a gentle series will easily reach young viewers.\\ ', '1', 'Laura Benanti', '179 phút', '2015-09-15', 'US', '465', null);
INSERT INTO `movie` VALUES ('34', 'Running Man (2010)', 'upload/Running Man (2010).jpg', 'Yu Jae Suk, Ji Suk Jin, Kim Jong Kook, Gary, Haha, Lee Kwang Soo, Song Ji-hyo,', 'Running Man (런닝 맨) is a real action program on Sunday afternoons SBS Good Sunday 1 part program. The MC and guests to play games and do the task, if victory will not incur a penalty. The program aired first time on 11/07/2010. Initially, the Running Man had 7 members Jaesuk Yoo, Ji Sukjin, Kim Jongkook, HaHa, Gary, Song Joong-ki, Lee Gwangsoo. From Episode 2 Song Jihyo join, become the 8th member of After School\'s Lizzy guesting sets 13, 14, 18, to set 19 becomes the 9th member of the Running Man. Due to busy personal activities and After School Lizzy formally withdraw from Running Man in episode 26 episode 41 end, Song also said goodbye to concentrate on her acting career. The Running Man Award and the cast has been achieved in the 4th SBS Entertainment Awards SBS New Star Variety Award: Song Joong-ki, Lee Kwang Soo, Gary Variety Special Award: Song Ji-hyo Best TV Star Award: Kim Jong-kook Most Popular Netizen Program: Running Man ', '5', 'Song Ji-hyo', '140 phút', '2015-10-13', 'Korea', '465', null);
INSERT INTO `movie` VALUES ('35', 'The Flash Season 2', 'upload/The Flash Season 2.jpg', 'Grant Gustin, Candice Patton, Danielle Panabaker, Carlos Valdes, Tom Cavanagh, Jesse L. Martin, Rick Cosnett, Malese Jow, Teddy Sears, Demore Barnes,', 'The Flash movies (Season 2) talk about Dr. Stein (Victor Garber) and Cisco (Carlos Valdez) is preparing \"welcomed\" a certain uninvited at STAR Labs. It was Jay\'s a mysterious character to Central city to warn Bary Allen and his team of the danger will occur in the near future. Besides, a new love story will be written up by Barry Allen and Patty Spivot, colleagues Inspector Eddie Joe West instead chet.Trong Part 2, the audience will admire the white badge Legendary instead the last red badge on the chest of The Flash Season 1. Be prepared sisters!', '1', 'Demore Barnes', '130 phút', '2015-09-15', 'US', '8657', null);
INSERT INTO `movie` VALUES ('36', 'THE WALKING DEAD SEASON 6', 'upload/THE WALKING DEAD SEASON 6.jpg', 'Andrew Lincoln, Jon Bernthal, Sarah Wayne Callies, Lauren Cohan, Chandler Riggs, Norman Reedus, Danai Gurira, Lennie James,', 'In The Walking Dead Season 6 this, Rick and the group members still have difficulty with the idea of uniformity in Alexandria residents. Does a new threat could help them unite together? Or will increasingly cause conflict between them further? - 5 actors in the cast will be elevated to the main character in the Season 6, which is: Lennie James (Morgan), Ross Marquand (Aaron), Tovah Feldshuh (Deanna), Alexandra Breckenridge (Jessie) and Austin Nichols (Spencer ). - Structure collective film will be extremely unique compared to previous episodes and was the first time the crew tested new storytelling. - Rick will face obstacles as hostility from one (number) residential People Alexandria - The episode will make audiences \"gasp\", fidgety during one week to wait two premiere episode to see what will come next. In other words, the first episode of season either but what \"First Time Again\" brings nothing short of a season finale. - All of the film the audience will be extremely pleased after watching this episode, even the difficult people and the most severe critic', '1', 'Lennie James', '120 phút', '2015-10-13', 'US', '65890', null);
INSERT INTO `movie` VALUES ('37', 'Fantastic Four: Rise of the Silver Surfer (2007)', 'upload/Rise of the Silver Surfer (2007).jpg', 'Kerry Washington\r\nAlicia Masters\r\nKerry Washington\r\nAlicia Masters\r\nKerry Washington\r\nAlicia Masters\r\n', 'Rise of the Silver Surfer (2007) CONTENT FILM Two years have passed since Victor Von Doom\'s evil name was super foursome turned into a statue made of iron. Reed Richards and Sue Storm are preparing for their wedding. At this moment, a strange silver objects appear on the atmosphere of the Earth, carrying giant energy sources, causing molecules oscillation phenomenon on a large scale, causing the Earth\'s crust are many cracks. A strange alien creatures capable of metamorphosis, going through all the material and features unparalleled power. He\'s estranged from one planet to the Earth outside the galaxy to prepare for the first Reconnaissance invasion destroyed. Besides Fantastic Four also take care of 1 rivals Dr. Doom always took the opportunity to find ways to harm them', '3', 'Tim Story, ', '130 phút', '2014-10-27', 'US', '7098', null);
INSERT INTO `movie` VALUES ('38', 'Scarlet Heart (2011)', 'upload/Scarlet Heart (2011).jpg', 'Dang Vi An, Ngo Cam Nguyen, Lam Ngoc Phan, Ly Quoc Lap, ', 'Zhang Understanding she was an ordinary office worker in a vibrant cities. Because accidentally fell into the tunnel of no return that timeless Qing Dynasty. There, she transforms into a young woman of sixteen downside Hi, caught up in the royal place with the fighting style kaleidoscope pattern. There were no gestures, gentle sweet words like other girls. However she was very saucy, often together with a shift \"to babble\", \"fight\" with all the women, to the Kangxi also called her \"Ten eighty daredevil\". Time fleeting, stubborn lady downside Hi every year has steadily grown. She caught up in the struggle for the throne of the prince\'s nine can not draw, personal feelings in the war torn place listing royal carpet .... glance cast Liu Shishi - Weak Hy / Zhang Understanding', '2', 'Lưu Tùng Nhân\r\nDận Tường', '170 phút', '2015-10-13', 'China', '349080', null);
INSERT INTO `movie` VALUES ('39', 'Violet & Daisy (2011)', 'upload/Violet & Daisy (2011).jpg', 'School Boy,Barbie Sunday', 'Just because fans Barbie pop singer Sunday, two friends named Violet and Daisy find ways to get the outfit to attend a concert of idols. Want to make money easily, both agreed to become hired assassins to kill Russ with the aim of a mysterious loner. But the girls did not expect this work to lead them to a crime beyond imagination. Like the girls the same age, they also love fashion and mischief. But while holding a gun in hand, Violet and Daisy became the face cold killer, willing to kill the target was hired. ', '4', 'Geoffrey Fletcher, ', '165 phút', '2015-10-13', 'US', '435', null);
INSERT INTO `movie` VALUES ('40', 'My Beautiful Bride (2015)', 'upload/My Beautiful Bride (2015).jpg', 'Park Hyeong-Sik,Seo Jin-Gi', 'Just because fans Barbie pop singer Sunday, two friends named Violet and Daisy find ways to get the outfit to attend a concert of idols. Want to make money easily, both agreed to become hired assassins to kill Russ with the aim of a mysterious loner. But the girls did not expect this work to lead them to a crime beyond imagination. Like the girls the same age, they also love fashion and mischief. But while holding a gun in hand, Violet and Daisy became the face cold killer, willing to kill the target was hired. ', '4', 'Kim Cheol-Kyu, ', '130 phút', '2015-09-15', 'Korea', '890', null);
INSERT INTO `movie` VALUES ('41', 'My Tutor Friend 2', 'upload/My Tutor Friend 2.jpg', 'Sun Poong-Gi,Jong-Man', 'My Tutor Friend 2 is part of the movie My Tutor Friend 2. To meet the dream lover, Junko decision from Japan to South Korea in its role as a student. Everything came to her very smoothly: a fully equipped hostel, a nice boss. Nothing to complain except for her in the room of the home ... son - Jong Man. In the eyes Junko, Jong Man is the worst men in her life she had ever seen. Pack all belongings in suitcases, Junko had to leave but an attractive offer \"full of lies\" by Jong Man were keeping back. Jong Man said that the room which was in previous Junko is where Seong Woo activities - whom Junko conduct affairs and determination to overcome the thousands of miles away to see ...', '3', 'Kim Ho-Jung, ', '120 phút', '2014-10-27', 'Korea', '980', null);
INSERT INTO `movie` VALUES ('43', 'ten 12343434234234', 'upload/aaa.jpg', 'dien', 'thong', '1', 'dao', '1110 Phut', '2015-12-01', 'phong cua toi', '4', 'upload/funny.mp4');

-- ----------------------------
-- Table structure for role
-- ----------------------------
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
  `Role_ID` int(11) NOT NULL,
  `Role_Name` varchar(255) NOT NULL,
  PRIMARY KEY (`Role_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of role
-- ----------------------------
INSERT INTO `role` VALUES ('1', 'Admin');
INSERT INTO `role` VALUES ('2', 'User');
